### ISSUE TITLE
Fails on macOS: tar: Option --warning=none is not supported

### ISSUE THREAD

**Issue by cakoose** [DefinitelyTyped/dts-critic#30]
I made a change to a DefinitelyTyped type definition.  I tried running the linter but it failed:

```
$ npm run lint ffi-napi

> definitely-typed@0.0.3 lint /Users/kannan/dev/DefinitelyTyped
> dtslint types "ffi-napi"

tar: Option --warning=none is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

I think `--warning=none` might be a non-standard option of GNU tar.  MacOS comes with BSD tar, which doesn't support that option.

That argument was added to dts-critic ~3 months ago: https://github.com/DefinitelyTyped/dts-critic/commit/cc2a731fbea0e0f7f755b12218b618030313923e

**Comment by sandersn** [comment]
`--warning=none` makes it so that tars created on (certain versions of?) macOS don't spew warnings when unpacked with GNU tar. Unfortunately both the devs on dts-critic use Linux, as does DT's CI, so we didn't notice the problem...

I think the best fix would just be OS detection since we use the flag because of incompatibilities between two platforms. I'm not sure what to do for windows, probably assume GNU semantics?

(Sorry for the delay, I've been caught up in urgent stuff at work.)
